DROP TABLE IF EXISTS detalle_compra CASCADE;
DROP TABLE IF EXISTS compra CASCADE;
DROP TABLE IF EXISTS empleado_contraseña CASCADE;
DROP TABLE IF EXISTS cliente_nit CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol CASCADE;

CREATE TABLE rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    numero VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL
);

CREATE TABLE proveedor (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proveedor VARCHAR(120) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    numero VARCHAR(20) NOT NULL
);

CREATE TABLE producto (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(140) NOT NULL,
    id_categoria INTEGER NOT NULL,
    id_proveedor INTEGER NOT NULL,
    grupo_kpop VARCHAR(80) NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria),
    CONSTRAINT fk_producto_proveedor
        FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor),
    CONSTRAINT chk_producto_precio CHECK (precio >= 0),
    CONSTRAINT chk_producto_stock CHECK (stock >= 0)
);

CREATE TABLE empleado_contraseña (
    id_empleado INTEGER PRIMARY KEY,
    password_hash VARCHAR(64) NOT NULL,
    CONSTRAINT fk_empleado_usuario
        FOREIGN KEY (id_empleado) REFERENCES usuario(id_usuario) ON DELETE CASCADE
);

CREATE TABLE cliente_nit (
    id_cliente INTEGER PRIMARY KEY,
    nit VARCHAR(20) UNIQUE,
    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (id_cliente) REFERENCES usuario(id_usuario)
);

CREATE TABLE compra (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_empleado INTEGER NOT NULL,
    fecha_compra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metodo_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pagada',
    CONSTRAINT fk_compra_cliente
        FOREIGN KEY (id_cliente) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_compra_empleado
        FOREIGN KEY (id_empleado) REFERENCES usuario(id_usuario),
    CONSTRAINT chk_compra_estado CHECK (estado IN ('pagada', 'anulada', 'pendiente'))
);

CREATE TABLE detalle_compra (
    id_compra INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    PRIMARY KEY (id_compra, id_producto),
    CONSTRAINT fk_detalle_compra
        FOREIGN KEY (id_compra) REFERENCES compra(id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
    CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_precio CHECK (precio_unitario >= 0)
);

CREATE INDEX idx_usuario_correo ON usuario(correo);
CREATE INDEX idx_producto_categoria ON producto(id_categoria);
CREATE INDEX idx_producto_proveedor ON producto(id_proveedor);
CREATE INDEX idx_compra_fecha ON compra(fecha_compra);
CREATE INDEX idx_detalle_producto ON detalle_compra(id_producto);

CREATE VIEW vista_resumen_ventas AS
SELECT
    c.id_compra,
    c.fecha_compra,
    cliente.nombre AS cliente,
    empleado.nombre AS empleado,
    c.metodo_pago,
    c.estado,
    COUNT(dc.id_producto) AS productos_distintos,
    SUM(dc.cantidad) AS unidades,
    SUM(dc.cantidad * dc.precio_unitario) AS total
FROM compra c
JOIN usuario cliente ON cliente.id_usuario = c.id_cliente
JOIN usuario empleado ON empleado.id_usuario = c.id_empleado
JOIN detalle_compra dc ON dc.id_compra = c.id_compra
GROUP BY c.id_compra, c.fecha_compra, cliente.nombre, empleado.nombre, c.metodo_pago, c.estado;

INSERT INTO rol (id_rol, nombre_rol) VALUES
  (1, 'Administrador'),
  (2, 'Empleado de caja'),
  (3, 'Cliente'),
  (4, 'Supervisor de tienda'),
  (5, 'Gerente');

INSERT INTO usuario (id_usuario, id_rol, nombre, correo, numero, activo)
SELECT
    i,
    CASE WHEN i = 1 THEN 1 WHEN i <= 25 THEN 2 ELSE 3 END,
    nombres[i],
    correos[i],
    '5025' || LPAD(i::TEXT, 7, '0'),
    TRUE
FROM generate_series(1, 50) AS i
CROSS JOIN (
    SELECT
        ARRAY[
            'Emily', 'Luis Angel', 'Valeria Choi', 'Mateo Lee', 'Camila Jung',
            'Andrea Han', 'Luis Kang', 'Mariana Song', 'Diego Moon', 'Lucia Hwang',
            'Carlos Min', 'Paola Ryu', 'Jose Baek', 'Gabriela Lim', 'Sebastian Jang',
            'Natalia Yoo', 'Emilio Kwon', 'Fernanda Seo', 'Ricardo Shin', 'Isabella Ko',
            'Alejandro Nam', 'Renata Cho', 'Oscar Jeon', 'Monica Ahn', 'Javier Won',
            'Ana Morales', 'Miguel Castillo', 'Diana Perez', 'Pablo Garcia', 'Laura Lopez',
            'Kevin Hernandez', 'Elena Ramirez', 'Hugo Santos', 'Marta Rivera', 'Ivan Ortiz',
            'Claudia Mejia', 'Roberto Vargas', 'Sara Alvarez', 'Julio Castro', 'Paula Flores',
            'Brenda Aguilar', 'Mario Cifuentes', 'Gaby Mendez', 'Cristian Rojas', 'Karla Soto',
            'Fernando Reyes', 'Angela Molina', 'Rene Pineda', 'Lourdes Fuentes', 'Esteban Cruz'
        ] AS nombres,
        ARRAY[
            'emily@kstoregalaxy.gt', 'luis.angel@kstoregalaxy.gt', 'valeria.choi@kstoregalaxy.gt',
            'mateo.lee@kstoregalaxy.gt', 'camila.jung@kstoregalaxy.gt', 'andrea.han@kstoregalaxy.gt',
            'luis.kang@kstoregalaxy.gt', 'mariana.song@kstoregalaxy.gt', 'diego.moon@kstoregalaxy.gt',
            'lucia.hwang@kstoregalaxy.gt', 'carlos.min@kstoregalaxy.gt', 'paola.ryu@kstoregalaxy.gt',
            'jose.baek@kstoregalaxy.gt', 'gabriela.lim@kstoregalaxy.gt', 'sebastian.jang@kstoregalaxy.gt',
            'natalia.yoo@kstoregalaxy.gt', 'emilio.kwon@kstoregalaxy.gt', 'fernanda.seo@kstoregalaxy.gt',
            'ricardo.shin@kstoregalaxy.gt', 'isabella.ko@kstoregalaxy.gt', 'alejandro.nam@kstoregalaxy.gt',
            'renata.cho@kstoregalaxy.gt', 'oscar.jeon@kstoregalaxy.gt', 'monica.ahn@kstoregalaxy.gt',
            'javier.won@kstoregalaxy.gt', 'ana.morales@mail.com', 'miguel.castillo@mail.com',
            'diana.perez@mail.com', 'pablo.garcia@mail.com', 'laura.lopez@mail.com',
            'kevin.hernandez@mail.com', 'elena.ramirez@mail.com', 'hugo.santos@mail.com',
            'marta.rivera@mail.com', 'ivan.ortiz@mail.com', 'claudia.mejia@mail.com',
            'roberto.vargas@mail.com', 'sara.alvarez@mail.com', 'julio.castro@mail.com',
            'paula.flores@mail.com', 'brenda.aguilar@mail.com', 'mario.cifuentes@mail.com',
            'gaby.mendez@mail.com', 'cristian.rojas@mail.com', 'karla.soto@mail.com',
            'fernando.reyes@mail.com', 'angela.molina@mail.com', 'rene.pineda@mail.com',
            'lourdes.fuentes@mail.com', 'esteban.cruz@mail.com'
        ] AS correos
) data;

INSERT INTO empleado_contraseña (id_empleado, password_hash)
SELECT
    i,
    CASE
        WHEN i = 1 THEN '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'
        ELSE 'ccc13e8ab0819e3ab61719de4071ecae6c1d3cd35dc48b91cad3481f20922f9f'
    END
FROM generate_series(1, 25) AS i;

INSERT INTO categoria (id_categoria, nombre_categoria, descripcion)
SELECT i, nombres[i], descripciones[i]
FROM generate_series(1, 25) AS i
CROSS JOIN (
    SELECT
        ARRAY[
            'Albums', 'Photocards', 'Lightsticks', 'Posters', 'Ropa',
            'Accesorios', 'Peluches', 'Stationery', 'DVD y Blu-ray', 'Vinilos',
            'Revistas', 'Season Greetings', 'Membership Kits', 'Llaveros', 'Stickers',
            'Fundas para celular', 'Bolsos', 'Joyeria', 'Cosmeticos', 'Snacks coreanos',
            'Preordenes', 'Ediciones limitadas', 'Fanmade', 'Conciertos', 'Combos'
        ] AS nombres,
        ARRAY[
            'Albumes fisicos con photobook y extras oficiales.',
            'Tarjetas coleccionables oficiales por integrante.',
            'Barras de luz oficiales para conciertos.',
            'Posters promocionales y de album.',
            'Hoodies, camisetas y prendas inspiradas en grupos.',
            'Pins, pulseras y accesorios de fandom.',
            'Muñecos y plushies de personajes oficiales.',
            'Cuadernos, lapiceros y papeleria tematica.',
            'Contenido audiovisual oficial.',
            'Versiones en vinilo de lanzamientos seleccionados.',
            'Revistas con portadas y entrevistas.',
            'Paquetes anuales de calendario y merch.',
            'Kits de membresia oficial para fandoms.',
            'Llaveros de logos, personajes y lightsticks.',
            'Stickers oficiales y decorativos.',
            'Cases y grips para celular.',
            'Tote bags y bolsos tematicos.',
            'Collares, aretes y charms.',
            'Productos de belleza coreanos relacionados.',
            'Snacks coreanos para eventos de fans.',
            'Productos reservados antes del lanzamiento.',
            'Merch de tiraje corto.',
            'Articulos creados por artistas locales.',
            'Entradas y paquetes de eventos.',
            'Bundles de productos con descuento.'
        ] AS descripciones
) data;

INSERT INTO proveedor (id_proveedor, nombre_proveedor, correo, numero)
SELECT
    i,
    nombres[i],
    LOWER(REPLACE(nombres[i], ' ', '.')) || '@proveedores-kpop.com',
    '5026' || LPAD(i::TEXT, 7, '0')
FROM generate_series(1, 25) AS i
CROSS JOIN (
    SELECT ARRAY[
        'Seoul Music Trade', 'Weverse Imports', 'JYP Goods Hub', 'SM Town Supply',
        'YG Select Central', 'KQ Merch Partners', 'Starship Goods', 'Cube Planet',
        'RBW Distribution', 'Pledis Shop', 'Kakao Entertainment', 'Mnet Plus Goods',
        'Ktown4u Wholesale', 'Music Korea Express', 'Soundwave Supply',
        'Makestar Global', 'Choice Music LA', 'SubK Shop Logistics',
        'Kpop Market Seoul', 'Withmuu Partners', 'Everline Merch',
        'Apple Music Korea', 'Dear My Muse', 'Fansign Studio GT', 'Local Fanart Studio'
    ] AS nombres
) data;

INSERT INTO producto (
    id_producto, nombre_producto, id_categoria, id_proveedor, grupo_kpop,
    precio, stock, descripcion
)
SELECT
    i,
    nombres[i],
    ((i - 1) % 25) + 1,
    ((i + 4) % 25) + 1,
    grupos[i],
    (80 + (i * 13 % 420))::NUMERIC(10, 2),
    18 + (i * 7 % 85),
    descripciones[i]
FROM generate_series(1, 50) AS i
CROSS JOIN (
    SELECT
        ARRAY[
            'BABYMONSTER DRIP Album', 'BLACKPINK BORN PINK Album',
            'TWICE CANDYBONG Infinity Light Stick', 'ILLIT SUPER REAL ME Album',
            'NewJeans Get Up Bunny Beach Bag Ver.', 'aespa Armageddon Album',
            'KiiiKiii UNCUT GEM Album', 'IVE I''VE MINE Album', 'BABYMONSTER DRIP Jewel Case',
            'LE SSERAFIM UNFORGIVEN Album', 'Hearts2Hearts The Chase Single Album',
            'Red Velvet Chill Kill Album', 'NMIXX Fe3O4: BREAK Album',
            'aespa Drama Album', 'ITZY BORN TO BE Album',
            'KISS OF LIFE Midas Touch Album', 'XG WOKE UP Album', 'MAMAMOO MIC ON Album',
            'NMIXX expergo Digipack', 'Korean Snack Fanbox', 'ILLIT SUPER REAL ME Weverse Albums Ver.',
            'KiiiKiii UNCUT GEM Photobook', 'Dreamcatcher Apocalypse: From us Album',
            'IU The Winning Album', 'Girl Group Starter Combo',
            'BABYMONSTER BABYMONS7ER Album', 'BLACKPINK KILL THIS LOVE Album',
            'TWICE READY TO BE Album', 'Hearts2Hearts The Chase Mini Book Ver.',
            'NewJeans OMG Album', 'Girls'' Generation FOREVER 1 Album',
            'KISS OF LIFE Sticky Album', 'IVE IVE SWITCH Album',
            'BABYMONSTER DRIP Bandana Ver.', 'LE SSERAFIM ANTIFRAGILE Album',
            'ILLIT SUPER REAL ME Poster', 'Red Velvet Cosmic Album',
            'NMIXX Fe3O4: STICK OUT Album', 'aespa Whiplash Album',
            'ITZY GOLD Album', 'XG AWE Album',
            'MAMAMOO reality in BLACK Album', 'KiiiKiii I DO ME Photocard Set',
            'NMIXX AD MARE Album', 'Hearts2Hearts The Chase Package Ver.',
            'KISS OF LIFE Born to be XX Album', 'Dreamcatcher VirtuouS Album',
            'IU Palette LP', 'STAYC Metamorphic Album', 'fromis_9 Supersonic Album'
        ] AS nombres,
        ARRAY[
            'BABYMONSTER', 'BLACKPINK', 'TWICE', 'ILLIT', 'NewJeans',
            'aespa', 'KiiiKiii', 'IVE', 'BABYMONSTER', 'LE SSERAFIM',
            'Hearts2Hearts', 'Red Velvet', 'NMIXX', 'aespa', 'ITZY',
            'KISS OF LIFE', 'XG', 'MAMAMOO', 'NMIXX', 'K-Food',
            'ILLIT', 'KiiiKiii', 'Dreamcatcher', 'IU', 'Varios',
            'BABYMONSTER', 'BLACKPINK', 'TWICE', 'Hearts2Hearts', 'NewJeans',
            'Girls'' Generation', 'KISS OF LIFE', 'IVE', 'BABYMONSTER', 'LE SSERAFIM',
            'ILLIT', 'Red Velvet', 'NMIXX', 'aespa', 'ITZY',
            'XG', 'MAMAMOO', 'KiiiKiii', 'NMIXX', 'Hearts2Hearts',
            'KISS OF LIFE', 'Dreamcatcher', 'IU', 'STAYC', 'fromis_9'
        ] AS grupos,
        ARRAY[
            'Album fisico con photobook, CD y photocards oficiales.',
            'Album fisico con photobook y componentes oficiales.',
            'Lightstick oficial con empaque y correa.',
            'Album debut con CD, photobook y photocards.',
            'Version Bunny Beach Bag del EP Get Up.',
            'Album fisico sellado con inclusiones aleatorias.',
            'Mini album debut con photobook y componentes.',
            'Album fisico de la era IVE MINE.',
            'Jewel case oficial de DRIP.',
            'Album fisico importado de la era UNFORGIVEN.',
            'Single album debut con The Chase y Butterflies.',
            'Calendario, diary y set de postcards.',
            'Album fisico de la serie Fe3O4.',
            'Album oficial de la era Drama.',
            'Album oficial de la era BORN TO BE.',
            'Single album oficial de Midas Touch.',
            'Single album oficial WOKE UP.',
            'Mini album oficial MIC ON.',
            'Digipack oficial de expergo.',
            'Caja de snacks para reuniones de fans.',
            'Version Weverse Albums de SUPER REAL ME.',
            'Photobook de coleccion de UNCUT GEM.',
            'Album fisico de la serie Apocalypse.',
            'Album fisico oficial de IU.',
            'Combo de album, poster y protector.',
            'Mini album oficial BABYMONS7ER.',
            'Album fisico de la era KILL THIS LOVE.',
            'Album sellado con inclusiones aleatorias.',
            'Version Mini Book del single album The Chase.',
            'Album fisico oficial OMG.',
            'Album FOREVER 1 version fisica.',
            'Single album oficial Sticky.',
            'Album fisico IVE SWITCH.',
            'Version Bandana del album DRIP.',
            'Album fisico de la era ANTIFRAGILE.',
            'Poster promocional de SUPER REAL ME.',
            'Album oficial con photobook.',
            'Album fisico de la serie Fe3O4.',
            'Mini album oficial Whiplash.',
            'Album oficial GOLD.',
            'Mini album oficial AWE.',
            'Album oficial reality in BLACK.',
            'Set de photocards inspirado en I DO ME.',
            'Single album debut AD MARE.',
            'Version Package del debut The Chase.',
            'Mini album oficial Born to be XX.',
            'Poster de Apocalypse en papel brillante.',
            'LP de coleccion para fans de IU.',
            'Album fisico Metamorphic.',
            'Single album fisico Supersonic.'
        ] AS descripciones
) data;

INSERT INTO cliente_nit (id_cliente, nit)
SELECT id_usuario, 'CF-' || LPAD((id_usuario * 37)::TEXT, 6, '0')
FROM usuario
WHERE id_usuario BETWEEN 26 AND 50;

INSERT INTO compra (id_compra, id_cliente, id_empleado, fecha_compra, metodo_pago, estado)
SELECT
    i,
    26 + ((i - 1) % 25),
    2 + ((i - 1) % 24),
    TIMESTAMP '2026-04-01 10:00:00' + ((i - 1) * INTERVAL '9 hours'),
    metodos[((i - 1) % 5) + 1],
    'pagada'
FROM generate_series(1, 30) AS i
CROSS JOIN (
    SELECT ARRAY['efectivo', 'tarjeta', 'transferencia', 'paypal', 'cuotas'] AS metodos
) data;

INSERT INTO detalle_compra (id_compra, id_producto, cantidad, precio_unitario)
SELECT
    c.id_compra,
    p.id_producto,
    ((c.id_compra + linea.linea) % 3) + 1,
    p.precio
FROM compra c
CROSS JOIN generate_series(1, 3) AS linea(linea)
JOIN producto p
    ON p.id_producto = ((c.id_compra * 3 + linea.linea - 1) % 50) + 1;

SELECT setval(pg_get_serial_sequence('rol', 'id_rol'), (SELECT MAX(id_rol) FROM rol));
SELECT setval(pg_get_serial_sequence('usuario', 'id_usuario'), (SELECT MAX(id_usuario) FROM usuario));
SELECT setval(pg_get_serial_sequence('categoria', 'id_categoria'), (SELECT MAX(id_categoria) FROM categoria));
SELECT setval(pg_get_serial_sequence('proveedor', 'id_proveedor'), (SELECT MAX(id_proveedor) FROM proveedor));
SELECT setval(pg_get_serial_sequence('producto', 'id_producto'), (SELECT MAX(id_producto) FROM producto));
SELECT setval(pg_get_serial_sequence('compra', 'id_compra'), (SELECT MAX(id_compra) FROM compra));
